# Generated by Django 2.1.7 on 2019-03-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='doors',
            new_name='actions_commands',
        ),
    ]
