# Generated by Django 2.1.7 on 2019-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0002_auto_20190305_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
