# Generated by Django 2.1.7 on 2019-03-11 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0003_auto_20190311_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intercom',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='intercom',
            name='macaddres',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='actioncommand',
            name='action_uri',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='actioncommand',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 20, 49, 20, 983872)),
        ),
        migrations.AlterField(
            model_name='intercom',
            name='address',
            field=models.GenericIPAddressField(default='192.168.1.10'),
        ),
        migrations.AlterField(
            model_name='intercom',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
