# Generated by Django 2.1.7 on 2019-03-11 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0006_auto_20190311_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='r_code',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='intercom',
            new_name='hwid',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 21, 16, 7, 533397)),
        ),
    ]
