# Generated by Django 2.1.7 on 2019-03-11 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0007_auto_20190311_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kind',
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 21, 23, 29, 525695)),
        ),
    ]
