# Generated by Django 2.1.7 on 2019-03-11 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0008_auto_20190311_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncommand',
            name='action_uri',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actioncommand',
            name='description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='barcode',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hwid',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 21, 28, 14, 881039)),
        ),
        migrations.AlterField(
            model_name='intercom',
            name='description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
