# Generated by Django 2.1.7 on 2019-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QARxisApp', '0009_auto_20190311_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
